services:
  papra-imap-ingestor2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./downloads:/app/downloads
      - ./ingestion/<ADD ORG ID HERE>:/ingestor
    env_file:
      - .env 
    restart: always
  papra:
    image: ghcr.io/papra-hq/papra:latest-root
    container_name: papra
    restart: unless-stopped
    ports:
      - 1221:1221
    environment:
      - AUTH_SECRET=<secret>
      - APP_BASE_URL=http://localhost:1221
      - INGESTION_FOLDER_IS_ENABLED=true
    volumes:
      - ./app-data:/app/app-data
      - ./ingestion:/app/ingestion