version: '3.8'

services:
  papra-imap-ingestor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./downloads:/app/downloads
    env_file:
      - .env
    restart: always